### PR TITLE
Siddhant

### PR DESCRIPTION
**Pull request by jalilel1913**
Merge Siddhant into root branch

### CODE REVIEW

**Review by siddhant-tripathy1 — COMMENTED** [review]
changes

**Review by siddhant-tripathy1 — COMMENTED** [review]
changes

**Review by siddhant-tripathy1 — APPROVED** [review]
did some changes

**Review by siddhant-tripathy1 — COMMENTED** [review]
changes

**Comment by jalilel1913** [comment]
aiI

**Comment by jalilel1913** [comment]
I am unsure of how to resolve these branch conflicts via command line...

I am closing this PR.

**Pull request closed without merging**
